name: CI-CD

# Dispara o workflow em push na branch "main", merge na branch "main" ou manualmente
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Job CI: Compilação e testes do projeto
  CI:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Faz o checkout do código-fonte do repositório
      - name: Checkout do código-fonte do repositório
        uses: actions/checkout@v4

      # Passo 2: Configura o JDK 17
      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Passo 3: Compila e testa o projeto usando Maven
      - name: Compilar e testar o projeto usando Maven
        run: mvn --batch-mode test

      # Passo 4: Publica relatórios de teste
      - name: Publicar relatórios de teste
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Relatórios de Teste
          path: target/surefire-reports/

      # Passo 5: Build e análise com o SonarCloud
      - name: Build e análise com o SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION_KEY }}

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      # Passo 1: Faz o checkout do código-fonte do repositório
      - name: Checkout do código-fonte do repositório
        uses: actions/checkout@v4
